language: go
go:
  - 1.8
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get -qq update
  - nvm install 8.0.0
install:
  - sudo apt-get install python3.6
script:
  - make all
  - make test
